# -*- coding: utf-8 -*-
"""fig_9_1_and_9_2_graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrWbGui1PTHx-OF-cyllGzYNY12uBJvi
"""

import numpy as np
import matplotlib.pyplot as plt
import os

plt.switch_backend('agg')  # non-interactive, reliable for save
plt.close('all')

# =============================================================================
# Figure 9.1: Stochastic Drift – Ant Colonies vs Late VOC
# =============================================================================
fig, ax = plt.subplots(figsize=(8, 6))

# Dummy data (replace with real ensemble X_i, Y_i from run_ensemble)
# Ants: tight cluster ~ high X, low Y
ants_x = np.random.normal(0.9, 0.05, 100)
ants_y = np.random.normal(0.4, 0.06, 100)

# Late VOC: wide smear ~ low X, high Y
voc_x = np.random.normal(0.3, 0.25, 100)
voc_y = np.random.normal(2.8, 0.8, 100)

ax.scatter(ants_x, ants_y, color='forestgreen', alpha=0.6, label='Ant colonies (low variance)')
ax.scatter(voc_x, voc_y, color='darkred', alpha=0.6, label='Late VOC (high variance)')

ax.set_xlabel('X – Economic Metabolism')
ax.set_ylabel('Y – Governance Density')
ax.set_title('Figure 9.1: Stochastic Drift – Probability Clouds on Compass Plane')
ax.legend()
ax.grid(True, alpha=0.3)

# Save
os.makedirs('figures', exist_ok=True)
fig.savefig('figures/fig_9_1_stochastic_drift.png', dpi=300, bbox_inches='tight', facecolor='white')
print("Figure 9.1 saved to figures/fig_9_1_stochastic_drift.png")

plt.show()  # for your view

# =============================================================================
# Figure 9.2: Hazard Rate Comparison – Weibull vs Gompertz
# =============================================================================
t = np.linspace(0, 1000, 500)

# Weibull example (ants-like: high k)
k_weib = 3.2
lambda_weib = 800
h_weib = (k_weib / lambda_weib) * (t / lambda_weib)**(k_weib - 1)

# Gompertz example (VOC-like: high b)
a_gomp = 0.0001
b_gomp = 0.012
h_gomp = a_gomp * np.exp(b_gomp * t)

fig, ax = plt.subplots(figsize=(8, 5))
ax.plot(t, h_weib, color='forestgreen', label=f'Weibull (k={k_weib}, ants-like)')
ax.plot(t, h_gomp, color='darkred', label=f'Gompertz (b={b_gomp}, VOC-like)')

ax.set_xlabel('Time (years)')
ax.set_ylabel('Hazard rate h(t)')
ax.set_yscale('log')
ax.set_title('Figure 9.2: Hazard Rate Comparison – Adaptive vs Rigid Decay')
ax.legend()
ax.grid(True, alpha=0.3)

fig.savefig('figures/fig_9_2_hazard_comparison.png', dpi=300, bbox_inches='tight', facecolor='white')
print("Figure 9.2 saved to figures/fig_9_2_hazard_comparison.png")

plt.show()

!git add figures/fig_9_*.png
!git commit -m "Add Ch. 09 figures: stochastic drift clouds and hazard rate comparison"
!git push origin main