# -*- coding: utf-8 -*-
"""fig_11_1_attractor_catalog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eoCQy4Y9oA2orePeQg-mFTX6bP7ILjor
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse, Rectangle
import os

# Non-linear penalty function (from compass protocol)
def apply_penalty(s):
    if abs(s) > 8:
        excess = abs(s) - 8
        return s - np.sign(s) * (excess ** 2 * 0.5)
    return s

plt.switch_backend('agg')
plt.close('all')

# CONFIG
CSV_FILES = [
    "data/35_metrics_ethereum_consensus.csv",
    "data/35_metrics_polkadot_consensus.csv",
    "data/35_metrics_ethereum_aihegemon_variant.csv"
]
REPLICATOR_NAMES = ["Ethereum", "Polkadot", "AI-Hegemon Variant"]
ENSEMBLE_N = 50
NOISE_STD = 0.07

# Attractor zones (rough illustrative boundaries)
ATTRACTORS = [
    {"name": "Mutualism Ellipsoid", "xy": (0.8, 0.5), "width": 0.6, "height": 1.0, "color": "limegreen", "alpha": 0.15},
    {"name": "Parasitism Sinkhole", "xy": (-0.6, 2.5), "width": 0.8, "height": 1.5, "color": "darkred", "alpha": 0.15},
    {"name": "Competition Toroid", "xy": (0.9, 1.8), "width": 0.5, "height": 0.8, "color": "orange", "alpha": 0.15},
    {"name": "Amensalism Channel", "xy": (-0.5, 1.0), "width": 0.7, "height": 1.2, "color": "gray", "alpha": 0.15},
    {"name": "Neutralism Void", "xy": (0.0, 0.0), "width": 0.4, "height": 0.6, "color": "lightgray", "alpha": 0.15},
    {"name": "Commensalism Plains", "xy": (0.4, 0.3), "width": 0.8, "height": 0.8, "color": "lightgreen", "alpha": 0.15},
    {"name": "Hybrid Lattice Band", "xy": (0.7, 1.2), "width": 1.0, "height": 0.8, "color": "cyan", "alpha": 0.15},
    {"name": "Rigidity Wall", "xy": (0.2, 2.8), "width": 0.4, "height": 0.6, "color": "purple", "alpha": 0.15},
    {"name": "Drift Corridor", "xy": (-0.3, -0.5), "width": 0.6, "height": 1.0, "color": "lightblue", "alpha": 0.15},
    {"name": "Bifurcation Ridge", "xy": (0.0, 1.5), "width": 0.5, "height": 0.8, "color": "yellow", "alpha": 0.15},
]

def rule13_proxy(s):
    g1 = s['G1']
    d1 = s['D1']
    return max(0, min(50, 50 - (g1 * 2 + (10 - abs(d1)) * 1.5)))

# Load & Generate Ensembles
all_points = []
all_proxies = []
all_labels = []

for csv_path, name in zip(CSV_FILES, REPLICATOR_NAMES):
    if not os.path.exists(csv_path):
        print(f"Error: {csv_path} not found")
        continue

    df = pd.read_csv(csv_path)
    scores = dict(zip(df['Metric'], df['Score']))

    # Base (penalized) X/Y
    x_metrics = [scores[m] for m in df['Metric'][:18]]
    y_metrics = [scores[m] for m in df['Metric'][18:]]
    base_x = np.mean([apply_penalty(s) for s in x_metrics]) / 10 * 1.2
    base_y = np.mean([apply_penalty(s) for s in y_metrics]) / 10 * 3.0

    # Noisy cloud
    x_cloud = []
    y_cloud = []
    proxy_cloud = []
    for _ in range(ENSEMBLE_N):
        noisy_scores = {m: s + np.random.normal(0, NOISE_STD) for m, s in scores.items()}
        noisy_x = np.mean([apply_penalty(noisy_scores[m]) for m in df['Metric'][:18]]) / 10 * 1.2
        noisy_y = np.mean([apply_penalty(noisy_scores[m]) for m in df['Metric'][18:]]) / 10 * 3.0
        proxy = rule13_proxy(noisy_scores)  # assuming rule13_proxy defined earlier

        x_cloud.append(noisy_x)
        y_cloud.append(noisy_y)
        proxy_cloud.append(proxy)

    all_points.append((x_cloud, y_cloud))
    all_proxies.append(proxy_cloud)
    all_labels.append(name)

# Plot
fig, ax = plt.subplots(figsize=(10, 8))

for (x_c, y_c), proxies, label in zip(all_points, all_proxies, all_labels):
    sc = ax.scatter(x_c, y_c, c=proxies, cmap='viridis', alpha=0.7, s=40, label=label)
    ax.scatter(np.mean(x_c), np.mean(y_c), color='black', marker='*', s=200, edgecolor='white', zorder=10)

ax.set_xlabel('X – Economic Metabolism')
ax.set_ylabel('Y – Governance Density')
ax.set_title('Figure 11.1: Phase-Space Attractor Catalog\nEnsemble Clouds (n=50 per replicator, σ=0.07)')

# Shaded zones
for zone in ATTRACTORS:
    patch = Ellipse(zone['xy'], zone['width'], zone['height'],
                    color=zone['color'], alpha=zone['alpha'], fill=True)
    ax.add_patch(patch)
    ax.text(zone['xy'][0], zone['xy'][1], zone['name'], fontsize=8, ha='center', va='center', color='black', alpha=0.8)

cbar = fig.colorbar(sc, ax=ax, label='Rule-13 Proxy (%)')
cbar.set_ticks([0, 10, 20, 30, 40, 50])
ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
ax.grid(True, alpha=0.3)

# Save
os.makedirs('figures', exist_ok=True)
save_path = 'figures/fig_11_1_attractor_catalog.png'
fig.savefig(save_path, dpi=300, bbox_inches='tight', facecolor='white')
print(f"Figure saved to: {save_path}")

plt.show()

!git add figures/fig_11_1_attractor_catalog.png
!git commit -m "Add Figure 11.1: Phase-Space Attractor Catalog for Ch. 11"
!git push origin main