# -*- coding: utf-8 -*-
"""fig_2_4_principate_drift_heatmap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oc5jrhSaZ1OJeuM0qy-iRHfwzrOMUCX3
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/15x6-sim
# or wherever you cloned it, e.g. /content/drive/MyDrive/Projects/15x6-sim
!pwd
!ls data/
!git clone https://github.com/MementoMori15x6/15x6-sim.git
# %cd 15x6-sim
!pip install pandas numpy matplotlib seaborn scipy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import LinearSegmentedColormap
import textwrap

# ────────────────────────────────────────────────
# Load Late Republic CSV from repo
url = 'https://raw.githubusercontent.com/MementoMori15x6/15x6-sim/main/data/35_metrics_roman_republic_133_27_bce.csv'
df = pd.read_csv(url)
scores = df['Score'].to_numpy(dtype=float)
assert len(scores) == 35

# Penalty function
def penalty(s):
    return s + np.sign(s) * (abs(s) - 8)**2 * 0.5 if abs(s) > 8 else s

adjusted = np.array([penalty(s) for s in scores])

# Rule-13 parasitism %
rule13_idx = [17,18,19,20,21,22,25]
rule13_norm = adjusted[rule13_idx] / 10
parasitism_pct = (np.sum(-rule13_norm[rule13_norm < 0]) / len(rule13_norm) if np.any(rule13_norm < 0) else 0) * 100

# Build matrix
rule_map = [[0,1,2],[5],[6],[7],[10],[3,4],[32],[9],[6],[11],[12],[13],[8,14],[15],[16]]
matrix = np.zeros((15,6))
for i, idxs in enumerate(rule_map):
    m = np.mean(adjusted[idxs]) / 10
    amt = abs(m) * 30
    delta = [amt,0,-amt,amt,-amt,0] if m > 0 else [-amt,0,amt,-amt,amt,0]
    row = (np.ones(6)*(100/6) + delta) / np.sum(np.ones(6)*(100/6) + delta) * 100
    matrix[i] = row

matrix[12,2] = parasitism_pct
matrix[12,[0,1,3,4,5]] = (100 - parasitism_pct) / 5

# ────────────────────────────────────────────────
# Heatmap with fixes for label cropping
rules = [
    "1. Harvest negative entropy",
    "2. Replicate with heredity",
    "3. Allow heritable variation",
    "4. Differential persistence",
    "5. Individual survival until replication",
    "6. Resource acquisition & defense",
    "7. Reproductive success",
    "8. Adaptation to change",
    "9. Diversity maintenance",
    "10. Niche construction & colonization",
    "11. Boundary maintenance",
    "12. Error detection & repair",
    "13. Cheater detection & suppression (KEY)",
    "14. Hierarchical/modular organization",
    "15. Info storage separated from execution"
]

# Wrap long labels
wrapped_rules = ['\n'.join(textwrap.wrap(r, width=25)) for r in rules]

moves = ["Mutualism (+/+)", "Commensalism (+/0)", "Parasitism (+/–)", "Competition (–/–)", "Amensalism (0/–)", "Neutralism (0/0)"]

df_grid = pd.DataFrame(matrix, index=rules, columns=moves)

mask = (df_grid == 0.0) | (df_grid < 0.01)

viridis_base = plt.cm.viridis
newcolors = viridis_base(np.linspace(0, 1, 256))
newcolors[0] = [1,1,1,1]
custom_map = LinearSegmentedColormap.from_list('WhiteViridis', newcolors)

fig, ax = plt.subplots(figsize=(14, 11))  # Slightly taller to help labels
ax.set_facecolor('#E6F5FF')

sns.heatmap(df_grid, annot=True, fmt=".1f", cmap=custom_map, mask=mask,
            vmin=0, vmax=100, linewidths=1, linecolor="#eeeeee", ax=ax)

ax.xaxis.set_ticks_position('top')
ax.xaxis.set_label_position('top')
ax.set_xticklabels(moves, rotation=45, ha="left", fontsize=10)

# Use wrapped labels
ax.set_yticklabels(wrapped_rules, rotation=0, va="center", fontsize=9)

# Extra padding for y-labels
ax.tick_params(axis='y', which='major', pad=20)

ax.set_title("Late Roman Republic (133–27 BCE): Separatrix Crisis", fontsize=20, pad=20)
ax.add_patch(plt.Rectangle((0,12),6,1, fill=False, edgecolor="#8B0000", lw=4, clip_on=False))

fig.text(0.53, -0.00,
         f"Critical Rule 13: >30 % Parasitism → Potential Collapse Risk | Entropy Export Ratio: {np.mean(matrix[:,0]) / (np.mean(matrix[:,2]) or 1e-6):.2f}",
         fontsize=9, color="#8B0000", ha='center', va='top', fontweight='bold')

plt.tight_layout()
plt.subplots_adjust(left=0.3)  # Key fix: extra left margin for wrapped labels
plt.savefig("late_republic_heatmap_fixed.png", dpi=300, bbox_inches="tight")
plt.show()

import matplotlib.pyplot as plt

# Data points from our forward drift sim (approximate smooth curve for clarity)
years_ce = [0, 50, 100, 150, 180, 193, 235, 245, 255, 265, 275, 285, 295, 300]
export_ce = [7.16, 6.5, 6.0, 5.5, 5.0, 4.5, 4.0, 3.8, 3.5, 3.2, 2.9, 2.6, 2.4, 2.2]
paras_ce = [4.4, 6.0, 8.0, 10.0, 12.0, 15.0, 18.0, 19.0, 20.0, 21.0, 21.5, 22.0, 22.5, 23.0]

fig, ax = plt.subplots(figsize=(14, 7))

# Main lines
ax.plot(years_ce, export_ce, label='Entropy Export Ratio', linewidth=3, color='blue')
ax.plot(years_ce, paras_ce, label='Rule-13 Parasitism %', linewidth=3, color='orange')

# Thresholds
ax.axhline(1.5, color='orange', ls='--', label='Early Warning ~1.5')
ax.axhline(1.1, color='red', ls='--', label='Crisis Threshold ~1.1')

# Historical shock annotations
ax.axvline(180, color='gray', ls=':', alpha=0.7, label='Commodus 180 CE')
ax.axvline(193, color='gray', ls=':', alpha=0.7, label='Year of Five Emperors 193 CE')
ax.axvline(235, color='gray', ls=':', alpha=0.7, label='Barracks Emperors 235 CE')

# Legionary pay-rise shock markers (recurring every 10 years post-235)
pay_rise_years = [245, 255, 265, 275, 285, 295]
for y in pay_rise_years:
    ax.axvline(y, color='darkred', ls='-', alpha=0.4, lw=1.5)
ax.axvspan(235, 300, alpha=0.08, color='red', label='Recurring Legionary Pay-Rise Shocks')

# Optional: annotate Aurelian floor if desired
ax.axvline(270, color='purple', ls='--', alpha=0.5, label='Aurelian Floor ~270 CE')

ax.set_xlabel('Year CE')
ax.set_ylabel('Value')
ax.set_title('Figure 2.4: Principate Forward Drift – Stability → Third Century Anarchy Cascade')
ax.legend(loc='upper left', fontsize=10)
ax.grid(True, alpha=0.3)
ax.set_ylim(0, 25)

plt.tight_layout()
plt.savefig("fig_2_4_principate_drift.png", dpi=300, bbox_inches="tight")
plt.show()