# -*- coding: utf-8 -*-
"""venice_republic_697–1797_heatmap_rc1_v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAXT3EBTsG0KTJdQ75MiHW0LH4aKm9XZ

35_metrics_Venice_Republic_697–1797 Heatmap Generator
"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib as mpl
from matplotlib.colors import LinearSegmentedColormap

# ────────────────────────────────────────────────
# 1. CANONICAL LABELS (no trailing dashes)
# ────────────────────────────────────────────────
rules = [
    "1. Harvest negative entropy",
    "2. Replicate with heredity",
    "3. Allow heritable variation",
    "4. Differential persistence",
    "5. Individual survival until replication",
    "6. Resource acquisition & defense",
    "7. Reproductive success",
    "8. Adaptation to change",
    "9. Diversity maintenance",
    "10. Niche construction & colonization",
    "11. Boundary maintenance",
    "12. Error detection & repair",
    "13. Cheater detection & suppression (KEY RULE)",
    "14. Hierarchical/modular organization",
    "15. Info storage separated from execution"
]

moves = [
    "Mutualism (+/+)",
    "Commensalism (+/0)",
    "Parasitism (+/–)",
    "Competition (–/–)",
    "Amensalism (0/–)",
    "Neutralism (0/0)"
]

# ────────────────────────────────────────────────
# 2. VENICE DOMINANCE MATRIX (your values)
# ────────────────────────────────────────────────
venice_matrix = np.array([
    [75.0, 10.0,  5.0, 10.0,  0.0,  0.0],
    [70.0, 15.0,  5.0, 10.0,  0.0,  0.0],
    [65.0, 10.0,  5.0, 20.0,  0.0,  0.0],
    [60.0, 15.0,  5.0, 20.0,  0.0,  0.0],
    [70.0, 10.0,  5.0, 15.0,  0.0,  0.0],
    [75.0, 15.0,  5.0,  5.0,  0.0,  0.0],
    [80.0, 10.0,  5.0,  5.0,  0.0,  0.0],
    [70.0, 15.0,  5.0, 10.0,  0.0,  0.0],
    [65.0, 10.0,  5.0, 20.0,  0.0,  0.0],
    [60.0, 15.0,  5.0, 20.0,  0.0,  0.0],
    [55.0, 10.0,  5.0, 30.0,  0.0,  0.0],
    [50.0, 15.0,  5.0, 30.0,  0.0,  0.0],
    [45.0, 10.0,  5.0, 40.0,  0.0,  0.0],
    [60.0, 15.0,  5.0, 20.0,  0.0,  0.0],
    [70.0, 10.0,  5.0, 15.0,  0.0,  0.0]
])

venice_df = pd.DataFrame(venice_matrix, index=rules, columns=moves)

# ────────────────────────────────────────────────
# 3. STYLING (matches blank v4)
# ────────────────────────────────────────────────
viridis_base = mpl.colormaps["viridis"]
newcolors = viridis_base(np.linspace(0, 1, 256))
newcolors[0, :] = [0.98, 0.98, 1, 1]  # Light tint at zero
custom_map = LinearSegmentedColormap.from_list('FullSaturation', newcolors)
oxford_red = "#8B0000"

# ────────────────────────────────────────────────
# 4. PLOTTING (Single heatmap, selective style)
# ────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(14, 10))
sns.heatmap(venice_df, annot=True, fmt=".1f", cmap=custom_map, vmin=0, vmax=100,
            linewidths=0.5, linecolor="#dddddd", cbar_kws={'label': '% Dominance', 'pad': 0.08}, ax=ax)

ax.set_title("Venice Republic (697–1797) – Mutualism Baseline\nY= -0.819 | Parasitism 12.5%",
             fontsize=18, pad=50, fontweight='bold')
ax.set_ylabel("Base Rules (Dec 2025 Canon)", fontsize=12)
ax.xaxis.set_ticks_position('top')
ax.xaxis.set_label_position('top')
plt.xticks(rotation=45, ha="left", fontsize=10)
plt.yticks(rotation=0, fontsize=10)
ax.tick_params(axis='y', which='major', pad=10)

# Rule 13 red border
ax.add_patch(plt.Rectangle((0, 12), 6, 1, fill=False, edgecolor=oxford_red, lw=5, clip_on=False))

# Provisional note at bottom (aligned left)
ax.text(0, 15.5, "Critical Rule 13: >30 % Parasitism → Potential Collapse Risk",
        fontsize=10, color=oxford_red, ha='left', va='top', fontweight='bold',
        bbox=dict(facecolor='white', edgecolor='none', alpha=0.7))

plt.tight_layout()
plt.savefig("venice_mutualism_baseline_v2.png", dpi=300, bbox_inches="tight")
plt.show()

print("Saved: venice_mutualism_baseline_v2.png")