# -*- coding: utf-8 -*-
"""simulate_v0.4_current_voc_lattice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifXQ1_LKPpUBHLBpsSKtjB_LCkrPld3e
"""

# Commented out IPython magic to ensure Python compatibility.
import os
from getpass import getpass

# 1. Clean up any previous failed attempts to avoid nesting
!rm -rf /content/15x6-sim
# %cd /content

# 2. Securely enter your credentials
user = "MementoMori15x6"
password = getpass('Paste your GitHub PAT here: ')
repo_name = "15x6-sim"

# 3. Build the authenticated URL
remote_url = f"https://{user}:{password}@github.com/{user}/{repo_name}.git"

# 4. Clone directly into /content/15x6-sim
!git clone {remote_url}

# 5. Move into the repo and identify yourself to Git
# %cd {repo_name}
!git config --global user.email "mementomori15x6@proton.me"
!git config --global user.name "MementoMori15x6"

print(f"✅ Successfully at: {os.getcwd()}")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/15x6-sim
!pwd
!ls -la   # should show data/, simulate.py, README.md, etc.

!git status

!git add data/35_metrics_voc_ensemble_consensus.csv

!git add .

!git commit -m "Add ensemble consensus 35-metric scoring for VOC (1602–1799) with synthesized rationales from 4 LLMs"

import pandas as pd

csv_path = 'data/35_metrics_voc_ensemble_consensus.csv'
df = pd.read_csv(csv_path)

print("Loaded successfully!")
print(df.shape)                  # Should be (35, 4)
print(df.columns.tolist())       # ['Metric', 'Description', 'Score', 'Rationale']
print("\nFirst few rows:\n", df.head())
print("\nScore stats:\n", df['Score'].describe())
print("\nMean A-G (econ, first 18):", df.iloc[0:18]['Score'].mean().round(3))
print("Mean H-M (gov, last 17):", df.iloc[18:]['Score'].mean().round(3))

# Commented out IPython magic to ensure Python compatibility.
# %run simulate.py

!python simulate.py data/35_metrics_voc_ensemble_consensus.csv

import pandas as pd
import numpy as np

# Load your VOC consensus
csv_path = 'data/35_metrics_voc_ensemble_consensus.csv'
df = pd.read_csv(csv_path)
print("VOC CSV loaded — shape:", df.shape)

scores = df['Score'].values.astype(float)
print("Scores extracted (first 5):", scores[:5])

# Non-linear penalty: amp extremes (|s| > 8) quadratic 0.5 coeff
penalized = np.copy(scores)
ext_mask = np.abs(scores) > 8
penalized[ext_mask] += np.sign(scores[ext_mask]) * 0.5 * (np.abs(scores[ext_mask]) - 8)**2

# Means
econ_mean = np.mean(penalized[:18])
gov_mean  = np.mean(penalized[18:])

x = econ_mean / 10 * 1.2
y = gov_mean  / 10 * 3.0

print("\n--- VOC Consensus Compass ---")
print(f"Penalized econ mean (A-G): {econ_mean:.3f}")
print(f"Penalized gov mean  (H-M): {gov_mean:.3f}")
print(f"Final X: {x:.3f}")
print(f"Final Y: {y:.3f}")

# Rule-13 proxy (G1 = index 15, negative → higher parasitism %)
g1 = scores[15]
parasitism_pct = max(0, -g1 * 3.5) + 25   # toy scaling to match ants ~0.6% example
print(f"Rule-13 parasitism proxy: ~{parasitism_pct:.1f}% (G1 = {g1:.1f})")

# Placeholder longevity (tune later vs known 197y)
long_base = 180 + (g1 * 5)   # weak G1 shortens
long_low  = long_base - 30
long_high = long_base + 40
print(f"Estimated longevity window: ~{long_low:.0f}–{long_high:.0f} years (actual 197 fits)")
print("Note: High suppression (Y deep negative) + scale leak suggests upper end optimistic.")

!head -n 50 simulate.py

!python -c "import sys; print(sys.argv)"

!python -c "import sys; print(sys.argv)" data/35_metrics_voc_ensemble_consensus.csv

!python simulate.py

# Commented out IPython magic to ensure Python compatibility.
# %run simulate.py data/35_metrics_voc_ensemble_consensus.csv

from IPython.display import Image, display
display(Image(filename="tests/outputs/35_metrics_voc_ensemble_consensus_lattice.png", width=900))
